---

- name: hoftix (ps3)
  block:
    - name: ensure temp directory exists
      ansible.windows.win_file:
        path: '{{ temp_cab_directory }}'
        state: directory

    - name: extract hotfix
      ansible.windows.win_shell: |
        Start-Process -FilePath 'wusa.exe' -ArgumentList '{{ hotfix_temp_directory }}\{{ hotfix_download.file }} /extract:{{ temp_cab_directory }}' -Wait

    - name: get cab files
      ansible.windows.win_find:
        paths: '{{ temp_cab_directory }}'
        patterns:
          - '*{{ hotfix_download.kb | upper }}*.cab'
          - '*{{ hotfix_download.kb | lower }}*.cab'
      register: get_cab_files

    - name: install hotfix
      ansible.windows.win_shell: dism.exe /online /NoRestart /add-package /PackagePath:{{ item.path }}
      loop: "{{ get_cab_files.files }}"
      register: hotfix_install
      failed_when:
        - hotfix_install.rc > 0
        - ('operation completed successfully' not in hotfix_install.stdout)

  always:
    - name: ensure temp directory removed
      ansible.windows.win_file:
        path: '{{ temp_cab_directory }}'
        state: absent
  vars:
    temp_cab_directory: '{{ temp_directory }}\{{ hotfix_download.kb }}'
